### ISSUE TITLE
Speed of coin is too fast

### ISSUE THREAD

**Issue by LukeBusuttil** [mabela25942/IMTAssignment2016#5]
The coin was falling too fast and needs to fall slower

**Comment by mabela25942** [comment]
The initial Coin speed was set to 6 and it was so fast that it didn't even appear on screen .. 

![screenshot 2016-05-25 00 00 23](https://cloud.githubusercontent.com/assets/11026341/15521455/2ddd25be-220c-11e6-8cf3-7b68cc39488e.png)

![screenshot 2016-05-25 00 00 27](https://cloud.githubusercontent.com/assets/11026341/15521398/d4de632e-220b-11e6-9fa3-55a9e03ae788.png)

The value of the speed was set to 3 on LV 1 and on lv 2 and 3 set to  5 as the lv gets harder..
