### ISSUE TITLE
Cannot shoot barrel

### ISSUE THREAD

**Issue by LukeBusuttil** [mabela25942/IMTAssignment2016#6]
When you shoot the barrel, the laser goes right through it and nothing happens this can be experienced in lv 1

**Comment by mabela25942** [comment]
The barrel was untagged in the inspector.. so i had to choose the tag that was created for it
![screenshot 2016-05-25 00 33 57](https://cloud.githubusercontent.com/assets/11026341/15522121/7a157158-2210-11e6-99f5-c555aa989f12.png)

![screenshot 2016-05-25 00 34 05](https://cloud.githubusercontent.com/assets/11026341/15522122/7ce05358-2210-11e6-84fd-fde51d3ea504.png)

Altough this was set .. the problem still persisted so i had to open the code .. and i found that i had called the wrong tag out .. as there was a spelling mistake .. 

![screenshot 2016-05-25 00 35 14](https://cloud.githubusercontent.com/assets/11026341/15522144/b22f86aa-2210-11e6-92cf-33b2f859c6e5.png)

![screenshot 2016-05-25 00 36 40](https://cloud.githubusercontent.com/assets/11026341/15522155/c6fdbbb0-2210-11e6-88c1-1602e796701e.png)
