### ISSUE TITLE
Missing power up

### ISSUE THREAD

**Issue by LukeBusuttil** [mabela25942/IMTAssignment2016#7]
The ammo power up is not visible in game ..

**Comment by mabela25942** [comment]
The ammo Power up was not selected in the inspector 

![screenshot 2016-05-25 00 49 51](https://cloud.githubusercontent.com/assets/11026341/15522440/ad7b2a36-2212-11e6-9dc2-c88592ee2354.png)

![screenshot 2016-05-25 00 49 53](https://cloud.githubusercontent.com/assets/11026341/15522441/afefbfde-2212-11e6-8c43-0c69fcf7c561.png)

After the ammo prefab was selected it was displayed instantly ..
