### ISSUE TITLE
Game end when player score is 5

### ISSUE THREAD

**Issue by LukeBusuttil** [mabela25942/IMTAssignment2016#8]
The game says that you have lost when the game score is 5..

**Comment by mabela25942** [comment]
When the game was being played i noticed that the score when it hit 5 the lost screen was being shown .. and there fore not switching to the lv 2 .. i also noticed when i removed the preview an error was being displayed that the string .. was obsolete .. 

![screenshot 2016-05-25 01 03 50](https://cloud.githubusercontent.com/assets/11026341/15522783/10103e6e-2215-11e6-9d27-bdda885e191d.png)

i went in the build setting and decided to change every string value into an integer .. 

![screenshot 2016-05-25 01 06 44](https://cloud.githubusercontent.com/assets/11026341/15522788/1624bdf2-2215-11e6-88dd-79a439b39c04.png)

The error disappeared and the level loaded successfully ..

![screenshot 2016-05-25 01 12 38](https://cloud.githubusercontent.com/assets/11026341/15522868/d0c82356-2215-11e6-82e6-86e4e3e4102d.png)
