### ISSUE TITLE
QUIT button doesn't Work in LV1..

### ISSUE THREAD

**Issue by LukeBusuttil** [mabela25942/IMTAssignment2016#9]
The button when pressed doesn't do anything ..

**Comment by mabela25942** [comment]
the button when pressed didn't do anything therefore i had to include the following code for it to work .. as i have forgotten to add it 

![screenshot 2016-05-25 10 38 21](https://cloud.githubusercontent.com/assets/11026341/15533460/09483dde-2265-11e6-988b-67bc16c767f4.png)
